In [2]:
import pandas as pd

qa = pd.read_csv('jokes.csv')

In [12]:
qa.drop('ID', axis=1)

,Question,Answer
0,Did you hear about the Native American man tha...,He nearly drown in his own tea pee.
1,What's the best anti diarrheal prescription?,Mycheexarphlexin
2,What do you call a person who is outside a doo...,Matt
3,Which Star Trek character is a member of the m...,Jean-Luc Pickacard
4,What's the difference between a bullet and a h...,A bullet doesn't miss Harambe
...,...,...
38264,Q: Why did the pacifist /b/tard try to calm ev...,He did it for the
38265,Q: Why can't Obama poke fun at himself?,A: Because that would be racist.
38266,Why is gambling not allowed in Africa?,Because there are too many cheetahs.
38267,What do you call three witches in a hot tub?,A self-cleaning coven.
38268,What do scientists use to measure a chicken's ...,An egg timer

In [13]:
df = pd.read_csv('shortjokes.csv')

In [14]:
df

            ID                                               Joke
0            1  [me narrating a documentary about narrators] "...
1            2  Telling my daughter garlic is good for you. Go...
2            3  I've been going through a really rough period ...
3            4  If I could have dinner with anyone, dead or al...
4            5     Two guys walk into a bar. The third guy ducks.
...        ...                                                ...
231652  231653                The Spicy Sausage by Delia Katessen
231653  231654  TIL That I Shouldn't have gone to law school, ...
231654  231655  What did the RAM stick say to the politician? ...
231655  231656  what do you call a play about victorian era me...
231656  231657  Calculus should be taught in every high school...

[231657 rows x 2 columns]

In [17]:
qa = qa.drop('ID', axis=1)

In [18]:
qa

,Question,Answer
0,Did you hear about the Native American man tha...,He nearly drown in his own tea pee.
1,What's the best anti diarrheal prescription?,Mycheexarphlexin
2,What do you call a person who is outside a doo...,Matt
3,Which Star Trek character is a member of the m...,Jean-Luc Pickacard
4,What's the difference between a bullet and a h...,A bullet doesn't miss Harambe
...,...,...
38264,Q: Why did the pacifist /b/tard try to calm ev...,He did it for the
38265,Q: Why can't Obama poke fun at himself?,A: Because that would be racist.
38266,Why is gambling not allowed in Africa?,Because there are too many cheetahs.
38267,What do you call three witches in a hot tub?,A self-cleaning coven.
38268,What do scientists use to measure a chicken's ...,An egg timer

In [4]:
cleanedqa = pd.read_csv('qajokes_cleaned.csv')

In [7]:
cleanedqa.drop(cleanedqa.columns[0], axis=1, inplace=True)

In [10]:
cleanedqa

,Did you hear about the Native American man that drank 200 cups of tea?,He nearly drown in his own tea pee.
0,What's the best anti diarrheal prescription?,Mycheexarphlexin
1,What do you call a person who is outside a doo...,Matt
2,Which Star Trek character is a member of the m...,Jean-Luc Pickacard
3,What's the difference between a bullet and a h...,A bullet doesn't miss Harambe
4,Why was the Ethiopian baby crying?,He was having a mid-life crisis
...,...,...
38263,Q: Why did the pacifist /b/tard try to calm ev...,He did it for the
38264,Q: Why can't Obama poke fun at himself?,A: Because that would be racist.
38265,Why is gambling not allowed in Africa?,Because there are too many cheetahs.
38266,What do you call three witches in a hot tub?,A self-cleaning coven.
38267,What do scientists use to measure a chicken's ...,An egg timer

In [11]:
cleanedqa.to_csv('qajokes_cleaned.csv', index_label=False)